### PR TITLE
DOCSINFRA-171 configure sandbox to preview new connectors homepage

### PR DESCRIPTION
**Pull request by mojavelinux**
* upgrade to Antora 2.3.0-alpha.1
* use multiple start paths to reduce docs-connectors-new to single entry
* switch to updated sandbox UI

### CODE REVIEW

**Comment by mojavelinux** [comment]
@fermujica There's no issue in JIRA for this. Could you create an issue titled "deploy connectors homepage to sandbox site" (or something similar). I'll then add the issue number to this PR.

Note that this PR is blocked by the following PRs:

* https://github.com/mulesoft/docs-connectors-new/pull/6
* https://github.com/mulesoft/docs-site-ui/pull/7

**Comment by fermujica** [comment]
> @fermujica There's no issue in JIRA for this. Could you create an issue titled "deploy connectors homepage to sandbox site" (or something similar). I'll then add the issue number to this PR.
> 
> Note that this PR is blocked by the following PRs:
> 
> * [mulesoft/docs-connectors-new#6](https://github.com/mulesoft/docs-connectors-new/pull/6)
> * [mulesoft/docs-site-ui#7](https://github.com/mulesoft/docs-site-ui/pull/7)

@mojavelinux I created [DOCSINFRA-171](https://www.mulesoft.org/jira/browse/DOCSINFRA-171)

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
@fermujica If you merge this, we should have a working sandbox environment with the new connectors homepage a few minutes later.

**Comment by mojavelinux** [comment]
Thanks @fermujica. The sandbox env is working!

**Pull request merged**
